### ISSUE TITLE
报错ReferenceError: FdfsClient is not defined

### ISSUE THREAD

**Issue by hongyuxuan** [ymyang/fdfs#3]
我就按照你的README一字不差写的，报错：
ReferenceError: FdfsClient is not defined
    at Object.<anonymous> (E:\程序设计\nodejs\test_upload\test_upload.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by ymyang** [comment]
文档中
var fdfs = require('fdfs');
这一行有误，应该改为：
var FdfsClient = require('fdfs');
谢谢！
