### ISSUE TITLE
调用append模式时出错

### ISSUE THREAD

**Issue by Sindcs** [ymyang/fdfs#7]
当我在调用upload append模式时首次添加数据后再调研append追加
反回的storage与首次上传的文件storage不是同一个，导致出现错误
如下
receive server packet headerBuffer: {"type":"Buffer","data":[0,0,0,0,0,0,0,0,100,2]}
{ Error: receive packet errno is: 2
    at _parseHeader (server\node_modules\fdfs\lib\protocol.js:334:19)
    at Socket.listener (node_modules\fdfs\lib\protocol.js:183:34)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20) errno: 2, code: 2 }
就目前观察是由于storage在每次追加时返回的不是源storage导致的，帮忙看看是不是？谢谢

**Comment by ymyang** [comment]
请参照测试用例中[test/FdfsTest.js](https://github.com/ymyang/fdfs/blob/master/test/FdfsTest.js)中的test uploadAppenderFile，对照参数是否正确
